### ISSUE TITLE
Leaking global declaration

### ISSUE THREAD

**Issue by young-steveo** [highrisehq/lufo#9]
The [`e` variable here](https://github.com/highrisehq/lufo/blob/master/jquery.lufo.js#L28) is getting set on the global scope.  This should probably be scoped to the plugin?

**Comment by gblakeman** [comment]
Not sure this is actually the case? Either way, no longer applicable.

**Comment by young-steveo** [comment]
It [was here](https://github.com/highrisehq/lufo/blob/e7d956992f08d2ee36e9b86afa46150d16aad83d/jquery.lufo.js#L28), but it looks like you've resolved it. 👍
